### PR TITLE
V2

### PR DESCRIPTION
**Pull request by computerjazz**
- Major perf improvements by using reanimated + rngh
  - NOTE: Requires reanimated `proc` to see the full perf improvement, which has not been released as of this writing https://github.com/kmagiera/react-native-reanimated/pull/354. 
- Typescript
- Rename "move" functions to "drag"

### CODE REVIEW

**Comment by rgoldiez** [comment]
This is great.  But shouldn't `package.json` include reanimated + rngh as dependencies?

**Comment by rgoldiez** [comment]
Also, are you planning to publish under a `v2` or `next` tag on npm?

**Comment by computerjazz** [comment]
@rgoldiez planning on jumping straight into v2 -- do you see any reason not to?
I could publish as `next` until reanimated 1.3 is released. Technically v2 does not depend on 1.3, but since it will contain `proc`s it speeds things up considerably.

**Comment by rgoldiez** [comment]
Im using v1.x in a project now. Looking forward to trying v2 when it’s ready for testing. 

Would you rather not publish until `reanimated@1.3`?

**Comment by computerjazz** [comment]
you can test now if you install reanimated off master. It should work even with the current reanimated release, you just won't get as good performance.

**Comment by computerjazz** [comment]
published `v2` as `next`

**Comment by lafiosca** [comment]
I tried out 1.x along with the typings from DT and immediately ran into a problem with dragged items being invisible (perhaps the same as #89 ). I saw you mention v2 in some possibly related issues and decided to try it out by removing what I had and installing `@next`. My app is already using react-native-reanimated 1.4.0 and react-native-gesture-handler 1.5.0, so I thought it would be relatively easy.

The first thing I noticed was that the built-in typings are a bit different and not as user-friendly (e.g., `renderItem` needs to return a `ComponentType` rather than a `JSX.Element`). The next thing I noticed were that `renderItem`'s `move` and `moveEnd` seem to be replaced by a single `drag` method which requires an index parameter (which I assume is the index of the item being dragged), and I was unsure how the lib would know when the drag was ending. I tried to press ahead anyway, but it didn't seem to work at all for me.

I'm attaching screen recordings of my app with v1 and v2 of the library. In the v1 example, you can see that I can long-press and then drag around an item (even though it becomes invisible) and the other items will flow around it nicely. (When I release the item, the list goes back to the original order because I am not doing anything in the handler functions yet.) In the v2 example, when I long-press an item, the dragged item vanishes, and all items above it immediately jump downward, leaving an empty slot at the top of the list. And in some cases, as you can see later in the v2 example, when I begin to drag one item, it breaks the whole list, and even regular taps stop working.

v1:
draggable-v1

v2:
draggable-v2

I was thinking about digging into the v1 code a bit more tomorrow to try to see if I could work out the vanishing item problem, but if v1 is a dead end and I should be focused on v2, I'd like to understand what I need to do to get things working and to see if I can help improve the TypeScript typings.

**Comment by computerjazz** [comment]
@lafiosca  Thanks for the detailed report -- do you have some code I can look at or run?

A few things I noticed:
- `drag` doesn't take any arguments: https://github.com/computerjazz/react-native-draggable-flatlist/blob/v2/index.tsx#L845 You'll call this in your longpress handler. It sounds like you're getting it confused with the `onDrag...` callbacks? https://github.com/computerjazz/react-native-draggable-flatlist/blob/v2/index.tsx#L78-L84

Please take a look at the updated example in the README: https://github.com/computerjazz/react-native-draggable-flatlist/tree/v2#example

I don't have any plans to keep working on v1, I'd suggest you fork if you're interested in working on it.

**Comment by lafiosca** [comment]
@computerjazz I don't have any reproduction code I can share with you yet, sorry. Maybe after I mess with it tomorrow.

If `drag` doesn't take any arguments, then I think the typings are wrong: https://github.com/computerjazz/react-native-draggable-flatlist/blob/19d17778b2ca13b86f2fc1f1b20c537d6cd88c41/index.tsx#L88

This would jive with the fact that the behavior was identical when I tried ignoring the TS complaints and calling drag without an argument. 😆

The example shows roughly what I'm doing (calling `drag` in the `onLongPress` of the individual item), so I imagine that the problems I'm having are related to the complex stylings around my list and items and/or some kind of conflict with the react-navigation gesture handling (given that this is in a tab stack).

**Comment by computerjazz** [comment]
ah yep, that type is wrong -- good catch!

A bad interaction with tab swipe gesture sounds likely -- can you try setting `swipeEnabled` to `false` on press in? https://reactnavigation.org/docs/en/material-top-tab-navigator.html#swipeenabled

Not sure if that'd change anything but worth a shot...nested gesture handlers can be difficult to coordinate 😬

**Comment by lafiosca** [comment]
@computerjazz I finally had a moment to check this out. Turns out I was wrong about this specific screen being in a tab stack. It's actually a modal on the top-level switch navigator. There is still gesture handling for modal screens (swipe down to dismiss modal), which I was able to disable in the navigator config for this screen, but it did not change/improve the behavior of the list. 

And to expand on my screen recordings and comments above, it seems the second time I start to drag an item on the list is when it freezes the list/screen entirely.

From here I'm not sure how to progress, and I feel I am probably polluting this issue. Unsure if I should start to dig into the v2 gesture code, open a new issue, or perhaps fork v1 and try to address my vanishing item problem there. I'm unsure which would be easiest for me while remaining helpful for you.

**Comment by computerjazz** [comment]
Ok, can you try rendering your list outside of ALL modals/navigators and see if the issue still persists? That might at least tell us whether the issue is in a bad interaction between nav gestures or if it's something about the list itself.

I'm not too worried about issue polluting, I opened this PR to be able to find and discuss bugs like this one, but if you want to continue this convo in a separate issue that'd be fine too.

**Comment by lafiosca** [comment]
With the current complexity of the app and the way that the structured data is being fetched via API, stored in redux, and referenced via navigation parameters, it was difficult to reliably rebuild this view outside of the navigators. I can't spend a lot more time messing with this right now, but here's what I got. The first long-press and drag looks great, and the callbacks are called fine. The second long-press sticks the item in the final slot of the list and freezes it there, similar to the previous bad behavior. One thing that differs though: the dragged item is still touchable at this point. Long-pressing it again does not do anything obvious, but I do see a message in the console log which seems to indicate the library still believes the frozen item is hovering:

```
 LOG  Begin dragging index 1
 LOG  End dragging from index 1 to index 2
 LOG  Begin dragging index 1
 LOG  ## attempt to call drag() on hovering component
```

draggable-v2-no-nav

The items being dragged are custom components consisting of `TouchableOpacity`s containing `View`s with nested `View`s, some of which contain more specific `TouchableOpacity`s and invisible `ActionSheet` components from react-native-actionsheet. In other words, I don't think there's anything too wild in there, as far as I recall.

I think, considering my own project needs, I'm going to roll my own custom solution for this screen for now and potentially revisit this later. Sorry that I can't be more help at the moment.

**Comment by lafiosca** [comment]
Ok because I'm too curious and couldn't leave well enough alone, I simplified the test more to just be color blocks of text, and I'm still having the issues:

draggable-v2-simple

The list code looks like:
```
						<DraggableFlatList<string>
							data={['foo', 'bar', 'baz']}
							renderItem={renderDraggableCard}
							keyExtractor={(item) => item}
							refreshControl={refreshControl}
							ListEmptyComponent={emptyView}
							onDragBegin={(index) => {
								console.log(`Begin dragging index ${index}`);
							}}
							onDragEnd={({ from, to }) => {
								console.log(`End dragging from index ${from} to index ${to}`);
							}}
						/>
```

The render function:
```
		const renderDraggableCard = ({
			item,
			index,
			drag,
			isActive,
		}: {
			item: string,
			index: number,
			drag: () => void,
			isActive: boolean,
		}) => (
			<TouchableOpacity onLongPress={drag}>
				<Text style={[
					{
						width: '100%',
						height: 150,
						margin: 8,
						padding: 12,
						fontSize: 36,
						backgroundColor: index === 0 ? 'blue' : index === 1 ? 'green' : 'red',
					},
					isActive ? { borderWidth: 8, borderColor: 'magenta' } : {},
				]}>
					{item}
				</Text>
			</TouchableOpacity>
		);
```

And then piece by piece I ripped everything out of the app and brought this up to the top level, surrounded only by a container view of `flex: 1` and no context providers. Still behaved like this.

I'm going to have to cut off the investigation here, but for reference, here are the relevant library versions I am using:

react-native 0.61.4
react-native-gesture-handler 1.5.0
react-native-reanimated 1.4.0
react-native-draggable-flatlist 2.0.1

**Comment by computerjazz** [comment]
@lafiosca thanks so much for the example! I can repro on my end now, but only when I _do not_ set state on drag end. This wasn't a use case I was planning for, since usually you want to update your list data in response to the drag, but agree it's definitely a bug. I will look into it — I'm hoping it's as easy as forcing a rerender on drag end, whether `data` prop changes or not.

Can you verify that it works when you set new data in `onDragEnd`?
Example here:
https://gist.github.com/computerjazz/436f513ef40d37dd7da0c4fbfd93c732

**Comment by computerjazz** [comment]
@lafiosca should be fixed in 2.0.2. Thanks!

**Comment by computerjazz** [comment]
Oh and I should probably make the docs more clear, but if you are not setting updated data as your data source after a drag, your list _will_ jump back to its original position. In other words -- the component tells you _what happened_ as a result of the drag, but you are responsible for updating the data source. Usually it's as simple as `onDragEnd={({ data }) => this.setState(data)}`

**Comment by lafiosca** [comment]
Glad that helped. I was definitely assuming the latter and intended on wiring up the data update later, just didn’t expect the lack of updating during my trial to cause a bug.

There was also the separate problem with something in the full-blown version of my app conflicting with the smooth item animations and positioning, but I’m probably not going to have time to dig in on that.

**Pull request merged**
