### PR TITLE
Add prop that disables dragging of list items

### PR DESCRIPTION
**Pull request by EthanJoyce**
A la issue #72

### CODE REVIEW

**Comment by computerjazz** [comment]
I'm not seeing the value in this prop -- why can't the list item component decide whether to call `drag` or not?

**Comment by EthanJoyce** [comment]
It's useful for instances where you need to toggle draggability for all props, e.g. for a list where you can only drag items when at least one is selected, or a similar reordering mode is activated.

You're right that this can be achieved on a per-component basis, but having a global switch makes the code cleaner for these situations where all components should be affected. This is just a small quality of life change.

**Comment by timorss** [comment]
Is there a solution to disable drag?

**Comment by EthanJoyce** [comment]
> Is there a solution to disable drag?

See issue #72. Just don't call the drag function in the list items onLongPress handler.

**Pull request closed without merging**
