### PR TITLE
Port to Reanimated v2 

### PR DESCRIPTION
**Pull request by computerjazz**
This rewrite takes advantage of the simpler API of reanimated v2.

- [x] Item can be dragged
- [x] Spacer is inserted with correct size/index
- [x] Placeholder is inserted at spacer index with correct size if `renderPlaceholder` exists on props
- [x] Item animates to correct place on drag end
- [x] List updates in response to dragged data
- [x] List autoscrolls when at top/bottom edge
- [x] Correct types
- [x] Perf: Clean up context state—create separate providers for things that change + things that don't
- [x] Perf: Ensure constant 60 fps frame rate
- [x] Code quality: simplify drag end logic (syncing JS/React rendering and animated value resetting to avoid flicker currently adds a lot of complexity)
- [x] Handle edge cases (gesture cancel/fail)

Bugfixes:
- [x] Fix flicker + buggy animations on next render after drag end
- [x] Fix placeholder flicker/render on start drag
- [x] Fix sporadic `undefined` item
- [x] Android active item zIndex on scroll

Blockers:
- [ ] Reanimated 2 performance: 
   - issue: https://github.com/software-mansion/react-native-reanimated/issues/1635
   - discussion: https://github.com/software-mansion/react-native-reanimated/discussions/1632

### CODE REVIEW

**Comment by nelsonprsousa** [comment]
https://blog.swmansion.com/announcing-reanimated-3-16167428c5f7
I guess we will soon be stuck, since REA v3 is almost here and v1 support is gone. We will have REAv2 support for a couple more releases, tho.

**Comment by computerjazz** [comment]
Yeah, I saw that. I'm planning on fixing up this branch as performant as I can get it and releasing it as v4. If there are still perf issues with reanimated v3 we'll have to solve them as they come.

**Comment by nelsonprsousa** [comment]
> Yeah, I saw that. I'm planning on fixing up this branch as performant as I can get it and releasing it as v4. If there are still perf issues with reanimated v3 we'll have to solve them as they come.

Would you say we have perf problems with how many items?

Also, what's the best way to contact you regarding adding paid features to this open source project?

**Comment by daheeahn** [comment]
I am very much looking forward to this version update. awesome!

**Comment by geroale** [comment]
We are also looking forward to this upgrade. A thousand thanks!

**Comment by mordechaim** [comment]
I tried using the latest beta.5 version but as soon as I touch any row item the entire app crashes (running Android)

```
Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.RuntimeException: Value is undefined, expected an Object

Error: Value is undefined, expected an Object
    at hostFunction (native)
  at void com.swmansion.reanimated.AndroidErrorHandler.raise(java.lang.String) (AndroidErrorHandler.java:6)
  at void com.swmansion.reanimated.Scheduler.triggerUI() (Scheduler.java:-2)
  at void com.swmansion.reanimated.Scheduler$1.run() (Scheduler.java:24)
  at void com.swmansion.reanimated.Scheduler$2.runGuarded() (Scheduler.java:43)
  at void com.facebook.react.bridge.GuardedRunnable.run() (GuardedRunnable.java:31)
  at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:883)
  at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:100)
  at void android.os.Looper.loop() (Looper.java:237)
  at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:8167)
  at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
  at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:496)
  at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1100)
```

**Comment by computerjazz** [comment]
>Will you remove simultaneousHandlers from PanGestureHandler in DraggableFlatList.tsx?

@topheroes why?

**Comment by KrisLau** [comment]
@computerjazz Relating to the performance, would you recommend upgrading to v4 or staying on v3 for now?

**Comment by computerjazz** [comment]
I think v4 is in a good place performance-wise, and I recommend upgrading, but you should definitely test for yourself. I will not be maintaining v3 going forward.

**Comment by lh9403** [comment]
> I tried using the latest beta.4 and beta.5 versions but as soon as I touch any row item the entire app crashes (running Android bare-bone React Native)
> 
> I can confirm this does not happen on beta.3.
> 
> ```
> Abort message: 'JNI DETECTED ERROR IN APPLICATION: JNI GetObjectRefType called with pending exception java.lang.RuntimeException: Value is undefined, expected an Object
> 
> Error: Value is undefined, expected an Object
>     at hostFunction (native)
>   at void com.swmansion.reanimated.AndroidErrorHandler.raise(java.lang.String) (AndroidErrorHandler.java:6)
>   at void com.swmansion.reanimated.Scheduler.triggerUI() (Scheduler.java:-2)
>   at void com.swmansion.reanimated.Scheduler$1.run() (Scheduler.java:24)
>   at void com.swmansion.reanimated.Scheduler$2.runGuarded() (Scheduler.java:43)
>   at void com.facebook.react.bridge.GuardedRunnable.run() (GuardedRunnable.java:31)
>   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:883)
>   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:100)
>   at void android.os.Looper.loop() (Looper.java:237)
>   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:8167)
>   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
>   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:496)
>   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1100)
> ```

Have you solved the same problem? Now I have to reduce it to v3, but v3 doesn't work properly on Android

**Pull request merged**
