### PR TITLE
Port to Reanimated v2

### PR DESCRIPTION
**Pull request by computerjazz**
This is a complete rewrite to take advantage of Reanimated v2, and to extract logic into separate hooks and components.
To be published as 3.0.0.

- [x] Item can be dragged
- [x] Spacer is inserted with correct size/index
- [x] Placeholder is inserted at spacer index with correct size if `renderPlaceholder` exists on props
- [x] Item animates to correct place on drag end
- [x] List updates in response to dragged data
- [x] List autoscrolls when at top/bottom edge
- [ ] Correct types
- [x] Perf: Clean up context state—create separate providers for things that change + things that don't
- [ ] Perf: Ensure constant 60 fps frame rate
- [ ] Code quality: simplify drag end logic (syncing JS/React rendering and animated value resetting to avoid flicker currently adds a lot of complexity)
- [ ] Handle edge cases (gesture cancel/fail)

Bugfixes:
- [ ] Fix flicker + buggy animations on next render after drag end
- [ ] Fix placeholder flicker/render on start drag
- [x] Fix sporadic `undefined` item
- [x] Android active item zIndex on scroll

### CODE REVIEW

**Comment by computerjazz** [comment]
v2 migration may be blocked until android performance issues are addressed: https://github.com/software-mansion/react-native-reanimated/discussions/1632

**Comment by nelsonprsousa** [comment]
> v2 migration may be blocked until android performance issues are addressed: [software-mansion/react-native-reanimated#1632](https://github.com/software-mansion/react-native-reanimated/discussions/1632)



> v2 migration may be blocked until android performance issues are addressed: [software-mansion/react-native-reanimated#1632](https://github.com/software-mansion/react-native-reanimated/discussions/1632)

I'd still be happy to help testing v3-beta 👍

**Comment by computerjazz** [comment]
@nelsonprsousa thanks! I'll let you know when it's ready to start testing.

**Comment by computerjazz** [comment]
quick update here, I'm giving priority to a v2-compatible rewrite in v1 before circling back to this: https://github.com/computerjazz/react-native-draggable-flatlist/pull/281

Besides v2 having some perf issues, the v1 update will lay the groundwork for most of the architectural changes here.

**Comment by LetUsGeek** [comment]
@computerjazz , please can you tell me if this new branch (which I understand would become the v3.0) will remove the warning "ReactNativeFiberHostComponent: Calling getNode() on the ref of an Animated component is no longer necessary. ...".

And sorry for the newbie question: can I install this branch to test it in advance ?

Many thanks

**Pull request closed without merging**
