### PR TITLE
#277 ReactNativeFiberHostComponent: Calling getNode()

### PR DESCRIPTION
**Pull request by Preeternal**

### CODE REVIEW

**Comment by Preeternal** [comment]
https://github.com/computerjazz/react-native-draggable-flatlist/issues/277

**Comment by pirroman** [comment]
Hello, @Preeternal! I tried to do that. I guess we really need a complete migration to RNR2.
```
$ tsc
src/index.tsx:569:34 - error TS2339: Property 'measureLayout' does not exist on type 'View'.

569         if (nodeHandle) viewNode.measureLayout(nodeHandle, onSuccess, onFail);
                                     ~~~~~~~~~~~~~

src/index.tsx:594:20 - error TS2339: Property 'measure' does not exist on type 'View'.

594       containerRef.measure((_x, _y, w, h) => {
                       ~~~~~~~

src/index.tsx:594:29 - error TS7006: Parameter '_x' implicitly has an 'any' type.

594       containerRef.measure((_x, _y, w, h) => {
                                ~~

src/index.tsx:594:33 - error TS7006: Parameter '_y' implicitly has an 'any' type.

594       containerRef.measure((_x, _y, w, h) => {
                                    ~~

src/index.tsx:594:37 - error TS7006: Parameter 'w' implicitly has an 'any' type.

594       containerRef.measure((_x, _y, w, h) => {
                                        ~

src/index.tsx:594:40 - error TS7006: Parameter 'h' implicitly has an 'any' type.

594       containerRef.measure((_x, _y, w, h) => {
                                           ~


Found 6 errors.
```

**Comment by Preeternal** [comment]
Seems I have an idea, I'll try

**Comment by Preeternal** [comment]
Cause this declaration in react-native-reanimated 
изображение

**Comment by computerjazz** [comment]
the rewrite will address this and be v1 backwards compatible: https://github.com/computerjazz/react-native-draggable-flatlist/pull/281

**Pull request closed without merging**
