### PR TITLE
tests: setup jest, testing library and add tests

### PR DESCRIPTION
**Pull request by brunohkbx**
This PR set up jest and testing library. I also added a snapshot test to get some coverage.
I'll work on adding more tests to cover the other cases into another PR just to keep things simple.

@computerjazz Can we run this on a CI? CircleCI for instance.

### CODE REVIEW

**Comment by computerjazz** [comment]
I appreciate the PR, but I haven't found snapshot tests to be useful in my experience -- I've never caught a bug because of failing snapshots, and developers tend to just update them whenever they fail.

What use case do you see snapshots being useful for here?

**Comment by brunohkbx** [comment]
@computerjazz I've added this snapshot test just to make things easier as I'll add tests to cover other scenarios such as on drag start, end, rendering placeholder, and so on.
But I can remove it if you want

**Comment by computerjazz** [comment]
ah ok, well, if creating those tests seem interesting/useful for you I'm open to setting that up. 
I'd gravitate towards github actions for CI.

**Comment by brunohkbx** [comment]
Sounds good.
That's just a way to contribute to the amazing work you did here. :smiley: 
Also, it'll make it easier to track bugs and breaking changes.

I'll work on that in the next few days. thank you

**Comment by brunohkbx** [comment]
Done @computerjazz. I was able to add a few scenarios but I couldn't cover others because of `Animated.Code` is mocked. Maybe when #245 got merged we can add a few more around the `componentDidUpdate`.

**Pull request merged**
