### PR TITLE
Add activeScale to scale rows during dragging

### PR DESCRIPTION
**Pull request by Fsarmento**
When user drags a row, if activeScale is set (ex: activeScale={1.03}), that row will scale to simulate elevation.

### CODE REVIEW

**Comment by computerjazz** [comment]
I appreciate the work you put into this but it can be achieved using the current component by animating before you call `move()` and resetting in `onMoveEnd`:

grow

**Comment by Fsarmento** [comment]
Hi @computerjazz , thanks for commenting. Does your example works well in Android? I'm asking because in Android overflow is "hidden" by default ([issue](https://github.com/facebook/react-native/issues/6802)), which may not allow the active row to scale properly if inside the hoverComponent Animated.View (line 326). 

If it does work well in Android, I would change only one thing then. The onMoveEnd you suggested to use is only called  in onReleaseAnimationEnd, after the animation to realign the rows has ended and the hoverComponent is set to null. In fact in your gif example the animation when you release the row
does not seam to work.

It would make more sense to start as soon as onPanResponderRelease is called (to have both animations in parallel). I would suggest to have a new parameter "onRowRelease" that is called in onPanResponderRelease.

Looking forward to hearing your thoughts.

This is an example of what I want to achieve:

**Comment by computerjazz** [comment]
sorry for the long delay. I've removed overflow hidden and I like the `onRowRelease` idea, feel free to PR that.

**Comment by computerjazz** [comment]
not a core feature to this package but you can roll your own without touching the package internals: https://gist.github.com/computerjazz/1df4a146bdb260882f52d8d565fd3558#file-drag-with-scale-effect-tsx

**Pull request closed without merging**
