### PR TITLE
feat(rewrite): convert to function components/hooks, separate concerns

### PR DESCRIPTION
**Pull request by computerjazz**
Main changes:
- moves logic from a single huge class component into several smaller, more maintainable components and hooks
- translate actual component instead of copy. Allows us to maintain state during drag. The following behavior would not have been possible before, since the swiped state would have been lost in the copy: 
rndfl-samecell

- adds "cell decorators" to provide an easy way to add common hover animations --  for example, wrapping `renderItem` in a `<ScaleDecorator>` component will automatically scale the active item (see above gif). Added scale, shadow, and opacity decorators, and developers may create their own custom decorators via `useOnCellActiveAnimation` hook.
- `onRef` prop now returns the underlying flatlist, not the ref-of-a-flatlist
- remove `layoutInvalidationKey`: we no longer need to force re-measurement, each cell now automatically re-measures on layout

This is the same basic structure as the open v2 migration PR but will likely be merged first due to v2 performance issues that could take a while to address in reanimated.

### CODE REVIEW

**Comment by computerjazz** [comment]
@nelsonprsousa although this isn't yet using reanimated v2 apis, this is going to be the actual `react-native-draggable-flatlist` 3.0.0. Would you still be willing to give it a test drive? Can be installed via `beta` npm tag (or in package.json currently at `3.0.0-beta.4`).

Once this lands it should be much easier to switch over to the v2 apis once the perf issues are ironed out.

**Comment by nelsonprsousa** [comment]
> @nelsonprsousa although this isn't yet using reanimated v2 apis, this is going to be the actual `react-native-draggable-flatlist` 3.0.0. Would you still be willing to give it a test drive? Can be installed via `yarn add react-native-draggable-flatlist@beta` npm tag (or in package.json currently at `3.0.0-beta.4`).
> 
> Once this lands it should be much easier to switch over to the v2 apis once the perf issues are ironed out.

Yes, I can try it and give some feedback! I am currently at vacations, but I can try it by Monday 👍

**Comment by nelsonprsousa** [comment]
> > @nelsonprsousa although this isn't yet using reanimated v2 apis, this is going to be the actual `react-native-draggable-flatlist` 3.0.0. Would you still be willing to give it a test drive? Can be installed via `yarn add react-native-draggable-flatlist@beta` npm tag (or in package.json currently at `3.0.0-beta.4`).
> > Once this lands it should be much easier to switch over to the v2 apis once the perf issues are ironed out.
> 
> Yes, I can try it and give some feedback! I am currently at vacations, but I can try it by Monday 👍

Update: Today I am completely out of time. Postponed to tomorrow.

@computerjazz can you please tell me how can I find the most updated beta.x version?

**Comment by computerjazz** [comment]
Thanks! The current beta can be either installed via `yarn add react-native-draggable-flatlist@beta` or by checking out npm "versions" tab: https://www.npmjs.com/package/react-native-draggable-flatlist

**Comment by nelsonprsousa** [comment]
Here are my findings:

On both iOS and Android and using <ScaleDecorator> I noticed that the opacity vanishes as soon as the drag starts. Not sure if it is expected.

On Android the drag when there's an autoscroll at the top/bottom edge feels weird. Seems there's a problem while swapping item positions. Works as expected swapping items without autoscrolling. Android specific.

iOS:

https://user-images.githubusercontent.com/8364345/117075682-291f9000-ad2d-11eb-812e-fb921b83231c.mov

Android:

https://user-images.githubusercontent.com/8364345/117075011-0b056000-ad2c-11eb-92ad-7b3c05b03e45.mov

Tested with react-native-reanimated v2.1.0 and beta.6.

@computerjazz would you like me to test something more specific?

**Comment by computerjazz** [comment]
Thanks so much for testing!

>On both iOS and Android and using I noticed that the opacity vanishes as soon as the drag starts. Not sure if it is expected.

Yeah, so since we're now translating the "actual" flatlist element instead of a copy of the element, the drag starts out with whatever opacity the TouchableOpacity has when the drag begins -- is that what you're referring to? If you prefer the previous behavior you could set a the `key` on the TouchableOpacity using `isActive` state. This might also be a good candidate for a new `CellDecorator` component.

>On Android the drag when there's an autoscroll at the top/bottom edge feels weird. Seems there's a problem while swapping item positions. Works as expected swapping items without autoscrolling. Android specific.

Good catch! will look into this.

I don't have specific test cases in mind -- this is a pretty huge rewrite so I'm mostly looking to smoke test it in different use cases and make sure nothing major broke.

**Comment by nelsonprsousa** [comment]
> Thanks so much for testing!
> 
> > On both iOS and Android and using I noticed that the opacity vanishes as soon as the drag starts. Not sure if it is expected.
> 
> Yeah, so since we're now translating the "actual" flatlist element instead of a copy of the element, the drag starts out with whatever opacity the TouchableOpacity has when the drag begins -- is that what you're referring to? If you prefer the previous behavior you could set a the `key` on the TouchableOpacity using `isActive` state. This might also be a good candidate for a new `CellDecorator` component.

The opacity changes when we click on the item, awesome 🚀 , but once we start dragging, it changes a littleeeeeeee bit. It's super hard to notice, maybe you need to look multiple times 😅 

Here's an example that hopefully it's easier to understand:

https://user-images.githubusercontent.com/8364345/117077711-849f4d00-ad30-11eb-9f54-0b89480f68c9.mov

P.S: Full screen may help checking the opacity's change.

**Comment by nelsonprsousa** [comment]
Well, maybe it's just my eyes, I am not sure anymore of what my eyes sees 😆

**Comment by computerjazz** [comment]
haha yeah, I see it -- this is just the default behavior of what a TouchableOpacity does when you start dragging it (since we were dragging copies before, this didn't happen). I'll have to think a bit about what the right thing to do here is. I don't want to hard-set a new `key` on the library side, because a user might not want the active component to be recreated with a new `key`, but I agree this isn't ideal behavior.

**Comment by nelsonprsousa** [comment]
> haha yeah, I see it -- this is just the default behavior of what a TouchableOpacity does when you start dragging it (since we were dragging copies before, this didn't happen). I'll have to think a bit about what the right thing to do here is. I don't want to hard-set a new `key` on the library side, because a user might not want the active component to be recreated with a new `key`, but I agree this isn't ideal behavior.

Well, I can live with it. It's something super tinny. Almost like a nice feature, really 😄 

Everything's looks okay except the swapping on Android. Are you able to reproduce it in the playground example?

**Comment by computerjazz** [comment]
yes i can repro the active item moving slightly on autoscroll. not yet sure what's causing it

**Comment by computerjazz** [comment]
So, I believe I fixed the android autoscroll jumpiness via https://github.com/computerjazz/react-native-draggable-flatlist/pull/281/commits/b8b5e21f800a437fba11f0823516c70b02c3bd79 and published on `beta` (`3.0.0-beta.7`), but I still don't understand why it's behaving the way it is 😅.

I'm using the same exact `Animated` node calculation— when it's defined globally and passed on context it exhibits the jumpy behavior on autoscroll, but when it's defined within each cell container it does not. ¯\\\_(ツ)_/¯ I'd prefer for it to be a global calculation to optimize perf, but I don't think this one change will make any actual difference.

I'll take a pass at the opacity behavior but I don't think I consider it a release blocker, since a) it's the default Touchable behavior and b) there's a workaround

**Comment by nelsonprsousa** [comment]
> So, I believe I fixed the android autoscroll jumpiness via [b8b5e21](https://github.com/computerjazz/react-native-draggable-flatlist/commit/b8b5e21f800a437fba11f0823516c70b02c3bd79) and published on `beta` (`3.0.0-beta.7`), but I still don't understand why it's behaving the way it is 😅.
> 
> I'm using the same exact `Animated` node calculation— when it's defined globally and passed on context it exhibits the jumpy behavior on autoscroll, but when it's defined within each cell container it does not. ¯\_(ツ)_/¯ I'd prefer for it to be a global calculation to optimize perf, but I don't think this one change will make any actual difference.

https://user-images.githubusercontent.com/8364345/117372449-716fb700-aec1-11eb-8ce2-1e6a5a7e42dd.mov

After a super quick test, Android still feels weird, not sure what's happening. v beta.7.

**Comment by computerjazz** [comment]
doh, ok maybe i need to test with a more expensive component to render. 
about how many items are in your list? anything unusual about your items? 
thanks for testing another round!

**Comment by nelsonprsousa** [comment]
> doh, ok maybe i need to test with a more expensive component to render.
> about how many items are in your list? anything unusual about your items?
> thanks for testing another round!

Only up to 5/6 items in the flatlist. Just usual thing's in the render method: some views and an image 🙄

**Comment by computerjazz** [comment]
how about those tabs? is that a react navigation tab navigator nested in a stack? what navigation library/version?

**Comment by nelsonprsousa** [comment]
I am using react-native-navigation and react-native-tab-view. Tomorrow I'll test without the tabs and get back to you 👍

**Comment by computerjazz** [comment]
Thanks! Please test on a physical device if possible.

**Comment by computerjazz** [comment]
hm I cold booted the emulator and now i can't reproduce the flicker on the react navigation project in the simluator either:
rndfl_cold_start

**Comment by Pix-00** [comment]
Hi,

Thanks for this awesome rewriting. But I found there is a problem that the newly added components (after the first rendering) will not able to drag. Although it do response to press and long press and will move to the correct position when the other dragged components moved.

**Comment by Pix-00** [comment]
oh.... I will do some further tests to see if that problem was caused by mobx.
________________________________

**Comment by computerjazz** [comment]
@Pix-00  thanks so much -- that helps a lot. I see a few issues in your sample app:
- It looks like your key extractor is not returning unique keys for each item -- every key is the same string: `μg/Lpg/mLnull` . Keys need to be unique and stable (i.e. not change when the item index changes) so you may need to generate a uuid alongside each item
- Mobx is a mutable data store, which doesn't work well with react-native-draggable-flatlsit -- this package relies on the `data` prop being an immutable array. 
- All callback functions should be wrapped in `useCallback` for performance.

I've made some changes to your snack here: https://snack.expo.io/@computerjazz/mad-croissant-keyextractor
To fix the mutable array issue I spread the mobx array into the `data` prop on every render, but that could but optimized further. It now works as expected:
rndfl_keyExtractor

**Comment by Pix-00** [comment]
Really appreciate for you time, helps me a lot.

I will fix callback functions across my project and find a better way to make Mobx array immutable.
The key extractor should works fine in the real project, as there are some extra code to check if there are duplicate sets of units -- and if is, popup a snack bar to reminder users etc... But thanks for remind me that.

**Comment by computerjazz** [comment]
OK I think I finally figured out why I'm seeing android working as expected and you're seeing the jumpy behavior @nelsonprsousa . Are you on react native < 64? It looks like animated values bound to autoscroll were fixed on android in 64.

Here's an example -- the following two videos are the exact same component, using RN 63 and RN 64 [gist here](https://user-images.githubusercontent.com/6730148/118411219-4c5d1000-b648-11eb-99de-c0328cc550a6.mp4
). I'm calling `scrollToOffset` a few times on mount. The right colored box is rendered within the list and is bound to the scroll offset so it _should_ remain stuck in place as the list autoscrolls  (the left colored box is just for reference). This "stuck in place" behavior is critical to make the dragged item stick in place under your finger without jank.
In RN 63, the box jumps on scroll:

https://user-images.githubusercontent.com/6730148/118411712-cabab180-b64a-11eb-87da-f3bf0b12a685.mp4


in RN 64 it does not:

https://user-images.githubusercontent.com/6730148/118411225-5121c400-b648-11eb-818e-17144184eead.mp4

I'm not sure about the root cause of the behavior change, but I'm inclined to just set RN64 as the "minimum supported version" for `react-native-draggable-flatlist` 3.0.0

**Comment by nelsonprsousa** [comment]
> OK I think I finally figured out why I'm seeing android working as expected and you're seeing the jumpy behavior @nelsonprsousa . Are you on react native < 64? It looks like animated values bound to autoscroll were fixed on android in 64.

Hi @computerjazz, thanks for getting back. Yes, I am using 0.63.4.

I am okay with the minimum supported version to be the last react native version 👍

Gonna give more feedback once I update it.

**Comment by jcgertig** [comment]
@computerjazz any updates on this?

**Comment by Pix-00** [comment]
Just a note:
react-native-reanimated has released new alpha versions (2.3.0-alpha.3)
It may solve the performance issue that mentioned previously.

**Comment by computerjazz** [comment]
The short update is: we found a bug that causes android jank on versions of React Native below 64 (see comment: https://github.com/computerjazz/react-native-draggable-flatlist/pull/281#issuecomment-841874260). So, I put the brakes on releasing for the time being, in part because Expo is not yet compatible with RN 64 and I'd rather not field a bunch of "android is messed up" issues. That said you can still use the beta and I would appreciate any feedback or bug reports: https://www.npmjs.com/package/react-native-draggable-flatlist

Once this rewrite is released and feeling solid, I'll probably turn my attention to updating it to reanimated 2, but I'm not exactly sure why folks are requesting that, since reanimated 1 is currently faster for this use case (unless the reanimated 2 beta actually did solve perf issues), and since reanimated 2 is backwards compatible there's nothing stopping anyone from using it in their draggable flatlist project.

**Pull request merged**
