### PR TITLE
Define lines undroppable

### PR DESCRIPTION
**Pull request by sandroferrari**
For my case, I need to restrict droppable indexes in the list.
So I imagine I'm not the only !

Hope this help.

### CODE REVIEW

**Comment by computerjazz** [comment]
Why can't you selectively update your `data` array in `onMoveEnd`? Ie. do not update it if the row should not be draggable.

**Comment by sandroferrari** [comment]
For UX purpose, I don't want to move the spacer (empty element) at undroppable index. 
With my pull request, the spacer doesn't move at specified indexes so the user see clearly that's not possible to drop the element at these indexes.

**Comment by philipstanislaus** [comment]
I'd love to see this implemented. @computerjazz any chance this could be merged?

**Comment by computerjazz** [comment]
not a core feature -- can be worked around by being creative in how you define your data and `renderItem()`

**Pull request closed without merging**
