### PR TITLE
Initial support for multicolumn

### PR DESCRIPTION
**Pull request by jeromecornet**
Fixes https://github.com/computerjazz/react-native-draggable-flatlist/issues/14
This is a first draft of a multicolumn implementation.

It isn't particularly pretty as the underlying blocks move down / up rather than in the corresponding direction, but at least it seems functional.

Comments, thoughts ?

### CODE REVIEW

**Comment by computerjazz** [comment]
hey sorry for the late reply. I don't have any plans to support multicolumn in this package, but that's awesome if you've got it working!

**Comment by jeromecornet** [comment]
👍 I ended up changing my app to use a single column, so I didn't make much progress on this anyway.

**Comment by rodgomesc** [comment]
i really need this feature

**Comment by jeromecornet** [comment]
@rodgomesc If you really need it, I would suggest you fork https://github.com/jeromecornet/react-native-draggable-flatlist/tree/multicolumn and fixup the code if something isn't working well for you. For the most part that code was functional when I used it in my app.

**Comment by rodgomesc** [comment]
Thanks for the suggestion

**Comment by rodgomesc** [comment]
@jeromecornet in your repo, this actually is supporting drag and drop from a column to another?

**Comment by jeromecornet** [comment]
It still manages a single list which happens to be laid out in 2 or more columns (it's backed by the multi-column flatlist https://facebook.github.io/react-native/docs/flatlist#numcolumns), so you can drag elements anywhere in that list whatever column they happen to be laid out in. This does not handle 2 independent lists that you can drag elements from one to the other (but this is out of scope for this package anyway)

**Pull request closed without merging**
